spring:
  application:
    name: Journaling App
  data:
    mongodb:
      uri: mongodb+srv://shivangkhanna140903:Shivang2006@cluster0.sekde.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-indexed-creation: true
  redis:
    host: localhost
    port: 6379
    # password: WQYsOCSY6SAQ0U6AK3mIJrIivpsVz5Q3
  mail:
    host: smtp.gmail.com
    port: 587
    username: shivangkhanna140903@gmail.com
    password: sypd bbaz lnkq selk
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
server:
  port: 8090
  servlet:
    context-path: /journal
